//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideAdmin.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionType
    {
        public SectionType()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public long SectionTypeId { get; set; }
        public string SectionTypeName { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
    }
}
