//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideAdmin.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Documents = new HashSet<Document>();
            this.Sections = new HashSet<Section>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public long UserId { get; set; }
        public long PersonId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
