//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideInfrastructure.Model.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUpMaster
    {
        public LookUpMaster()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public long LookupId { get; set; }
        public string Name { get; set; }
        public string DataValue { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
    }
}
