//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideInfrastructure.Model.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionAttribute
    {
        public SectionAttribute()
        {
            this.SectionAttributeValues = new HashSet<SectionAttributeValue>();
        }
    
        public long SectionAttributeID { get; set; }
        public long SectionTypeId { get; set; }
        public long AttributeId { get; set; }
    
        public virtual LookUpMaster LookUpMaster { get; set; }
        public virtual LookUpMaster LookUpMaster1 { get; set; }
        public virtual ICollection<SectionAttributeValue> SectionAttributeValues { get; set; }
    }
}
