//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideInfrastructure.Model.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionDocument
    {
        public long SectionId { get; set; }
        public long DocumentId { get; set; }
        public string Description { get; set; }
    }
}
