//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideInfrastructure.Model.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.SectionAttributeValues = new HashSet<SectionAttributeValue>();
        }
    
        public long SectionId { get; set; }
        public string SectionName { get; set; }
        public string SectionDescription { get; set; }
        public Nullable<long> UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<long> SectionTypeId { get; set; }
        public int Status { get; set; }
    
        public virtual LookUpMaster LookUpMaster { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SectionAttributeValue> SectionAttributeValues { get; set; }
    }
}
