//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideInfrastructure.Model.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIDEContxts : DbContext
    {
        public SIDEContxts()
            : base("name=SIDEContxts")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentType> DocumentTypes { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<SectionDocument> SectionDocuments { get; set; }
        public DbSet<SectionType> SectionTypes { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
